--Explore all objects in the database
select * from INFORMATION_SCHEMA.tables

--Explore the columns
select * from INFORMATION_SCHEMA.columns
where table_name='dim_customers'

--Explore all countries our customers come from
select distinct country from gold.dim_customers

--Explore all Categories 'The major Divisions'
select distinct category,subcategory,product_name  from gold.dim_products
order by 1,2,3

--Find the date of the first and last order
select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
DATEDIFF(year,min(order_date),max(order_date)) as order_range_years
from gold.fact_sales

--Find the youngest and oldest customer
select min(birthdate),max(birthdate),
DATEDIFF(year,min(birthdate),GETDATE()) as oldest_age,
DATEDIFF(year,max(birthdate),GETDATE()) as youngest_age
from gold.dim_customers

--Find the total sales
select sum(sales_amount) as total_sales from gold.fact_sales

--FInd how many items are sold
select sum(quantity) as total_iterms from gold.fact_sales

--find the avg selling price
select avg(price) as avg_price from gold.fact_sales

--find the total nr of orders
select count(distinct order_number) as total_orders from gold.fact_sales

--find the total nr of products
select count(distinct product_key) as total_products from gold.dim_products

--find the total nr of customers
select count(distinct customer_key) as total_customers from gold.dim_customers

--find the total nr of customers that has placed an order
select count(distinct customer_key) as total_customers from gold.fact_sales 



--Generatea Report that shows all key metrics of the bussiness
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
UNION ALL
select 'Total Quantity' as measure_name, sum(quantity) from gold.fact_sales
UNION ALL
select 'Average Price' as measure_name, avg(price)  from gold.fact_sales
UNION ALL
select 'Total Nr. Orders' as measure_name, count(distinct order_number)  from gold.fact_sales
UNION ALL
select 'Total Nr. Products' as measure_name ,count(distinct product_key)  from gold.dim_products
UNION ALL
select 'Total Nr. Customers' as measure_name ,count(distinct customer_key) from gold.dim_customers


--Find the total nr of customers by countries
select 
country,count(customer_key) as total_customers
from gold.dim_customers group by country

--Find total customers by gender
select gender,count(customer_key) as total_customers
from gold.dim_customers group by gender

--find total products by category
select category,count(product_key) as total_products
from gold.dim_products group by category

--what is the avg cost in each category
select category,avg(cost) from gold.dim_products group by category

--What is the total revenue generated for each category
select 
sum(f.sales_amount) as total_revenue,
p.category 
from gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
group by p.category
order by total_revenue desc

--What is the total revenue generated by each customer
select 
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

--Which 5 products generate the highest revenue
select top 5
sum(f.sales_amount) as highest_revenue,
p.product_name
from gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
group by p.product_name
order by highest_revenue desc

--What are the 5 worst performing products in terms of sale
select top 5
sum(f.sales_amount) as highest_revenue,
p.product_name
from gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
group by p.product_name
order by highest_revenue 

--Find the top 10 customers who have generated the highest revenue
-- and 3 customers with the fewest orders placed
select top 10
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

select top 3
c.first_name,
c.last_name,
count(distinct order_number) as orders_placed
from gold.dim_customers c
LEFT JOIN gold.fact_sales f 
ON c.customer_key=f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by orders_placed
